language: php

php:
  - 7.1
  - 7.2

addons:
  chrome: stable

branches:
  - master

before_install:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update

install:
  - composer self-update
  - composer install --prefer-dist --no-interaction

sudo: true

cache:
  directories:
    - $HOME/.composer/cache

script:
  - composer lint
  - vendor/bin/phpunit
